<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../plugin/EntitySelectionRules.cs" Link="EntitySelectionRules.cs" />
    <Compile Include="../../plugin/Settings.cs" Link="Settings.cs" />
    <Compile Include="../../plugin/VersionInfo.cs" Link="VersionInfo.cs" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
</Project>
